remove unnecessary require() override
I started getting an error during `meteor test-packages ./`, probably
after adding `'use strict';`. Here's the error:

    /home/adamm/.meteor/packages/meteor-tool/.1.0.43.faq1kd++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:245
                                               throw(ex);
                                                     ^
    ReferenceError: require is not defined
        at Package (packages/csats:mturk/lib/js/mturk.js:3:1)
        at /tmp/meteor-test-runh7h2o4/.meteor/local/build/programs/server/packages/csats_mturk.js:1162:4
        at /tmp/meteor-test-runh7h2o4/.meteor/local/build/programs/server/packages/csats_mturk.js:1171:3
        at /tmp/meteor-test-runh7h2o4/.meteor/local/build/programs/server/boot.js:222:10
        at Array.forEach (native)
        at Function._.each._.forEach (/home/adamm/.meteor/packages/meteor-tool/.1.0.43.faq1kd++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
        at /tmp/meteor-test-runh7h2o4/.meteor/local/build/programs/server/boot.js:117:5